check:
  - thoth-build
  - thoth-precommit-py38
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.20.1
  build-stratergy: Source # Allowed values: Source, Dockerfile, Containerfile (default: Source)
  registry: quay.io # Imgage registry to be used. (default: quay.io)
  registry-org: thoth-station # Organization to be used in Image Registry. (default: thoth-station)
  registry-project: thoth-issue-predicator # Project Repository in Image Registry to be used to push image.
  registry-secret: thoth-station-thoth-pusher-secret # pre-exists in ci
